Changed MinimumVersion from number to string
  Encountered the following errors when attempting to run recipe:

    Traceback (most recent call last):
      ...snip...
      File "/Library/AutoPkg/autopkglib/__init__.py", line 420, in version_equal_or_greater
        return LooseVersion(this) >= LooseVersion(that)
      ...snip...
      File "/Library/AutoPkg/Python3/...snip.../distutils/version.py", line 314, in parse
        components = [x for x in self.component_re.split(vstring)
    TypeError: expected string or bytes-like object

  After some debugging noticed that the YAML value for MaximumVersion
  was actually as a float, and the Python LooseVersion() function
  requires a string.

  Placed the MaximumVersion value in double quotes.